///  Given two strings s and t which consist of only lowercase letters.
/// String t is generated by random shuffling string s and then add one more letter at a random position.
/// Find the letter that was added in t.

class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        let sumS = s.unicodeScalars.reduce(0, { $0 + $1.value })
        let sumT = t.unicodeScalars.reduce(0, { $0 + $1.value })
        return Character(UnicodeScalar(sumT-sumS)!)
    }
}